services:
  redis:
    image: "redis"
    container_name: translate-redis
    ports:
      - "6900:6379"
  worker:
    build: .
    command: ["celery", "--app=src.celery_app.app", "worker", "--loglevel=info"]
    image: translate-worker
    container_name: translate-worker
    depends_on:
      - redis
  api:
    build: .
    command: ["fastapi", "run", "src/api/main.py" ]
    image: translate-api
    container_name: translate-api
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - worker